import './header.js';
import './cart.js';
import './filter.js';
import './galery.js';
import './product-card.js';
import './footer.js';
import './details.js';
import './checkout.js';
import './faqs.js';